#!/usr/bin/env python3
"""
Layer 5 - Quarterly Patterns Report
Generates deep analysis of grant patterns from past quarter.
"""

import json
import sys
import logging
from datetime import datetime

from grants_context import grants_path

GRANTS_ROOT = grants_path()

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("quarterly_patterns")


def generate_quarterly_report(quarter=None):
    """Generate quarterly patterns report"""
    year = datetime.now().year
    if quarter is None:
        now = datetime.now()
        quarter = f"Q{(now.month - 1) // 3 + 1}"

    logger.info(f"Generating {quarter} patterns report")

    all_grants = []
    months = ["01", "02", "03"]
    current_month = datetime.now().strftime("%Y-%m")

    for month in months:
        month_str = f"{year}-{month}"
        if month_str > current_month:
            continue

        enriched_file = GRANTS_ROOT / "data" / "enriched" / month_str / "grants-enriched.json"
        if enriched_file.exists():
            with enriched_file.open("r", encoding="utf-8") as f:
                all_grants.extend(json.load(f))

    if not all_grants:
        logger.warning("No data found for quarterly report")
        return False

    patterns = {}
    funders = {}
    total_fit = 0
    high_fit_count = 0

    for g in all_grants:
        for p in g.get("intelligence", {}).get("pattern_matches", []):
            patterns[p] = patterns.get(p, 0) + 1

        f = g.get("funder", "Unknown")
        funders[f] = funders.get(f, 0) + 1

        fit = g.get("intelligence", {}).get("fit_score", 0)
        total_fit += fit
        if fit >= 7:
            high_fit_count += 1

    avg_fit = total_fit / len(all_grants) if all_grants else 0

    report = f"""---
quarter: {quarter}
generated: {datetime.now().isoformat()}
---

# Quarterly Grant Patterns Report - {quarter} {year}

*Generated: {datetime.now().strftime("%Y-%m-%d")}*

---

## Summary Statistics

| Metric | Value |
|--------|-------|
| Total Grants Analyzed | {len(all_grants)} |
| Average Fit Score | {avg_fit:.1f}/10 |
| High-Fit Grants (7+) | {high_fit_count} |
| Unique Funders | {len(funders)} |

---

## Top Patterns Identified

"""

    sorted_patterns = sorted(patterns.items(), key=lambda x: x[1], reverse=True)
    for p, count in sorted_patterns[:10]:
        report += f"- **{p}**: {count} grants\n"

    report += "\n## Top Funders\n\n"

    sorted_funders = sorted(funders.items(), key=lambda x: x[1], reverse=True)
    for f, count in sorted_funders[:10]:
        report += f"- **{f}**: {count} grants\n"

    report += f"""
---

## Recommendations

1. Focus on grants with pattern: {sorted_patterns[0][0] if sorted_patterns else "N/A"}
2. Prioritize funders with highest success rate
3. Build pipeline for {quarter} based on identified patterns

---

*Report generated by Cerebro-Skill integration*
"""

    reports_dir = GRANTS_ROOT / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    output_file = reports_dir / f"{year}-{quarter}-patterns.md"
    with output_file.open("w", encoding="utf-8") as f:
        f.write(report)

    logger.info(f"Quarterly report saved to {output_file}")

    with open(GRANTS_ROOT / "logs" / "quarterly-reports.log", "a") as f:
        f.write(
            f"{datetime.now().isoformat()} - Quarterly report generated - {len(all_grants)} grants analyzed\n"
        )

    return True


if __name__ == "__main__":
    quarter = sys.argv[1] if len(sys.argv) > 1 else None
    success = generate_quarterly_report(quarter)
    sys.exit(0 if success else 1)
